course_code <- "ECE421"
course_full_name <- "Introduction to Machine Learning"
university <- "University of Toronto (Downtown)"
department <- "Electrical and Computer Engineering"
season <- "Fall"
year <- "2024"
zoom_lec_l <- "https://utoronto.zoom.us/j/84800897084"
quercus_l <- "https://q.utoronto.ca/courses/363844"
crowdmark_l <- "https://crowdmark.com"